-- Local development seed. Reference data (grades, subjects, resource types,
-- curricula, periods, commission settings) is created by the migrations.
-- Demonstration shops and products will be added here in Phase 2 and will be
-- clearly marked as demo data; this file must never be run against production.
